### ISSUE TITLE
Package name discrepancy between npm/browserify usage and component/bower

### ISSUE THREAD

**Issue by TooTallNate** [twolfson/computedStyle#6]
This leads to code using this module being incompatible with one or the other builder.

npm/browserify:

``` js
var computedStyle = require('computed-style');
```

component/bower:

``` js
var computedStyle = require('computedStyle');
```

IMO the best fix is to update the `"name"` field on `component.json` and `bower.json` to be `computed-style` instead of `computedStyle`. This way, code written using `require('computed-style')` will be compatible with all builders.

**Comment by twolfson** [comment]
I am guessing I was trying to be clever at the time of writing (to make it closer to `getComputedStyle`). I agree with the recommendation of `dash-case` for all. I will take a look at fixing that by the end of this weekend.

**Comment by TooTallNate** [comment]
Sounds good! Would you like a pull request?

**Comment by twolfson** [comment]
Nah, I should be fine. Thanks though =)

**Comment by twolfson** [comment]
Augh, this is going to be more complicated than I thought. I think I need to create a new repo entirely. Also, it looks like there already is a `computed-style` in component which could cause issues =/

We could use `try { } catch (err) { }` for determining the module but that is horrible hack.

I am going to think for a bit.

**Comment by twolfson** [comment]
@TooTallNate Would you be interested in forking instead? Currently, I am maintaining this repo rather than using it.

Most of my hesitation is coming from not touching the `testling` integration in a while and I recall it being a pain to debug.

**Comment by TooTallNate** [comment]
> Also, it looks like there already is a `computed-style` in component which could cause issues =/

component is namespaced by username, so no, it's not an issue.

> Most of my hesitation is coming from not touching the `testling` integration in a while and I recall it being a pain to debug.

the changes i'm proposing are to the `bower.json` and `component.json` files, so testling wouldn't be affected by that.

**Comment by twolfson** [comment]
While the dependencies are namespaced by user, I think the components are installed to the same top level directory without the user. That way the `require` doesn't need the namespace.

Do you need `component` support? If not, I am going to consider dropping it.

**Comment by twolfson** [comment]
I brought up the `testling` integration because I was considering renaming the repo to make the `bower`/`component` names consistent with the GitHub repo since those are both `git` based. Renaming the repo would likely break existing hooks.

**Comment by TooTallNate** [comment]
We ended up going with https://www.npmjs.com/package/computed-style-component. I guess nothing needs to be done here afterall...

**Comment by twolfson** [comment]
Cool, works for me =)
